# version format
version: 1.0.{build}

# set clone depth
clone_depth: 5

environment:
  access_token:
    secure: pEozEGTqJutQwOidJU6BTB+Ix0NV4vrUnomhfeqheVz4RNwfxjEYLoqR4XabhlPz

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src\UmbracoArchiveProcessor.sln
  verbosity: minimal

# scripts to run before build
before_build:
  nuget restore src\UmbracoArchiveProcessor.sln
  
# scripts to run after build
after_build:
  cmd: src\UmbracoArchiveProcessor\bin\Release\uap.exe

# to disable automatic tests 
test: off

artifacts:
  - path: artifacts\**\*

deploy:
  provider: FTP
  protocol: sftp
  host:
    secure: nq7K4A9kQeSJ5/qrA1SL+uwuBKVmqIWtSygU3Z3iLjg=
  username:
    secure: tfL7blohLyft9yGHzsMVMg==
  password:
    secure: 9aI0ok+tlzT7fSVots8zIQ==
  folder:
    secure: o0ZdkUcM8vRmyFW+QvRT5DghZkrOIsXuvOVrKbsFHO5zuIzb8fKDIVv9NG7h5f7GZBRDza4A54atTT8cg9yfqQ==
  artifact:

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "leekelleher@gmail.com"
  - git config --global user.name "leekelleher"
  - git checkout master
  - git add data/releases.json
  - git commit -m "Updated releases.config [skip ci]"
  - git push origin master
