# version format
version: 1.0.{build}

# fetch repository as zip archive
shallow_clone: true 

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src\UmbracoArchiveProcessor.sln
  verbosity: minimal

# scripts to run before build
before_build:
  nuget restore src\UmbracoArchiveProcessor.sln
  
# scripts to run after build
after_build:
  cmd: src\UmbracoArchiveProcessor\bin\Release\uap.exe

# to disable automatic tests 
test: off

artifacts:
  - path: artifacts\**\*.*
